
// This file has been generated by the GUI designer. Do not modify.
public partial class MainWindow
{
	private global::Gtk.VBox vbox1;
	private global::Gtk.HBox TopButtonContainer;
	private global::Gtk.Button button2;
	private global::Gtk.Button ScanForAssetsButton;
	private global::Gtk.Button StartWebserverButton;
	private global::Gtk.ScrolledWindow GtkScrolledWindow;
	private global::Gtk.TextView logTextBox;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("MainWindow");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.TopButtonContainer = new global::Gtk.HBox ();
		this.TopButtonContainer.Name = "TopButtonContainer";
		this.TopButtonContainer.Spacing = 6;
		// Container child TopButtonContainer.Gtk.Box+BoxChild
		this.button2 = new global::Gtk.Button ();
		this.button2.CanFocus = true;
		this.button2.Name = "button2";
		this.button2.UseUnderline = true;
		this.button2.Label = global::Mono.Unix.Catalog.GetString ("GtkButton");
		this.TopButtonContainer.Add (this.button2);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.TopButtonContainer [this.button2]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child TopButtonContainer.Gtk.Box+BoxChild
		this.ScanForAssetsButton = new global::Gtk.Button ();
		this.ScanForAssetsButton.CanFocus = true;
		this.ScanForAssetsButton.Name = "ScanForAssetsButton";
		this.ScanForAssetsButton.UseUnderline = true;
		this.ScanForAssetsButton.Label = global::Mono.Unix.Catalog.GetString ("Scan For Assets");
		this.TopButtonContainer.Add (this.ScanForAssetsButton);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.TopButtonContainer [this.ScanForAssetsButton]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child TopButtonContainer.Gtk.Box+BoxChild
		this.StartWebserverButton = new global::Gtk.Button ();
		this.StartWebserverButton.CanFocus = true;
		this.StartWebserverButton.Name = "StartWebserverButton";
		this.StartWebserverButton.UseUnderline = true;
		this.StartWebserverButton.Label = global::Mono.Unix.Catalog.GetString ("Start WebServer");
		this.TopButtonContainer.Add (this.StartWebserverButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.TopButtonContainer [this.StartWebserverButton]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		this.vbox1.Add (this.TopButtonContainer);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.TopButtonContainer]));
		w4.Position = 0;
		w4.Expand = false;
		w4.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.logTextBox = new global::Gtk.TextView ();
		this.logTextBox.CanFocus = true;
		this.logTextBox.Name = "logTextBox";
		this.GtkScrolledWindow.Add (this.logTextBox);
		this.vbox1.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.GtkScrolledWindow]));
		w6.Position = 1;
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.DefaultWidth = 400;
		this.DefaultHeight = 300;
		this.button2.Hide ();
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.ScanForAssetsButton.Clicked += new global::System.EventHandler (this.OnScanForAssetsButtonClicked);
		this.StartWebserverButton.Clicked += new global::System.EventHandler (this.OnButton2Clicked);
	}
}
